nuxeo/nuxeo-elements

wct.conf.json
Goal is to integrate SauceLabs to do multi browser testing.
Currently this includes local Chrome and Firefox and remote Edge (Windows 10), IE 11 (Windows 8.1), Safari 11 (Mac OS  10.13), Safari on iPad and Android 6.0.
=> SauceLabs integration

nuxeo-page-provider.html
=> imp-NXP-25158-noAggs

nuxeo-page-provider.html
=> fix-ELEMENTS-708-selectivityReset

nuxeo-page-provider.html
=> fix-ELEMENTS-708-selectivityReset-9.10

nuxeo-operation.html, nuxeo-page-provider.html, test/nuxeo-operation.html
Depends on https://github.com/nuxeo/nuxeo/pull/2531
=> ELEMENTS-805: allow page provider input in operation

nuxeo-operation.html
Depends on https://github.com/nuxeo/nuxeo/pull/2538.
Based on https://github.com/nuxeo/nuxeo-elements/pull/40
=> ELEMENTS-806: async operation

nuxeo-page-provider.html, test/nuxeo-page-provider.html
Pipeline: https://qa.nuxeo.org/jenkins/job/web-ui-pipeline-ncunha/51/
=> ELEMENTS-781: rethrow page provider fetch error

ui/widgets/nuxeo-uploader-behavior.js
=> imp-NXP-26620-abortUpload

dataviz/nuxeo-aggregate-data-behavior.js, dataviz/package.json, dataviz/test/.eslintrc.json, dataviz/test/nuxeo-audit-data-test.html, dataviz/test/nuxeo-repository-data-test.html, dataviz/test/nuxeo-search-data-test.html, dataviz/test/nuxeo-workflow-data-test.html
=> fix-ELEMENTS-923-timezoneAgg

ui/nuxeo-page-provider-display-behavior.js
=> fix-ELEMENTS-942-domFlush

ui/nuxeo-user-group-management/nuxeo-user-management.js, ui/widgets/nuxeo-selectivity.js, ui/widgets/nuxeo-user-suggestion.js
Proposed solution for [ELEMENTS-916](https://jira.nuxeo.com/browse/ELEMENTS-916).
Feedback would be greatly appreciated. Thank you!
=> ELEMENTS-916: remove preserve-white-space class on nuxeo-selectivity selected items

ui/widgets/nuxeo-selectivity.js
Proposed solution for [ELEMENTS-919](https://jira.nuxeo.com/browse/ELEMENTS-919).
Feedback would be greatly appreciated. Thank you!
=> ELEMENTS-919: allow new entries in nuxeo-selectivity when using data instead of operation

.gitignore, core/nuxeo-connection.js
Angular needs time to bind and set information like url, username and password. Web Elements (like nuxeo-connection) needs to observe them.
=> ELEMENTS-955: Angular problem fixing

.gitignore, core/nuxeo-connection.js
Reverts nuxeo/nuxeo-elements#84
=> Revert "ELEMENTS-955: Angular problem fixing"

ui/nuxeo-data-table/data-table-checkbox.js, ui/nuxeo-data-table/data-table-row.js, ui/nuxeo-data-table/iron-data-table.js
=> ELEMENTS-913: use prototype chain check instead of tags

ui/actions/nuxeo-delete-document-button.js
=> task-ELEMENTS-953-hardDeleteNavigate

ui/demo/nuxeo-user-tag/index.html, ui/test/nuxeo-user-tag.test.js, ui/widgets/nuxeo-user-avatar.js, ui/widgets/nuxeo-user-group-formatter.js, ui/widgets/nuxeo-user-tag.js
=> fix-ELEMENTS-945-UserContainingNullName

ui/nuxeo-page-provider-display-behavior.js
=> fix-ELEMENTS-964-maxItemsConfig

dataviz/package.json, storybook/package.json, ui/package.json
=> fix-NXP-27703-elements-version

ui/widgets/nuxeo-file.js
=> fix-ELEMENTS-980-fileWidgetComplexProp

core/nuxeo-connection.js
=> fix-ELEMENTS-996-form-auth

ui/i18n/messages.json, ui/nuxeo-page-provider-display-behavior.js
=> fix-ELEMENTS-973-i18nPageProviderMessages

ui/actions/nuxeo-add-to-collection-button.js
=> fix-ELEMENTS-1021-UndefinedCollectionId

core/test/test-helpers.js, ui/actions/nuxeo-delete-document-button.js, ui/test/nuxeo-delete-document-button.test.js
=> fix-ELEMENTS-1010-DeleteButtonPermissions

ui/nuxeo-slots.js, ui/test/nuxeo-actions-menu.test.js, ui/test/nuxeo-slots.test.js
=> fix-ELEMENTS-1012-slot-name

ui/nuxeo-filter.js, ui/nuxeo-filters-behavior.js, ui/test/nuxeo-filter.test.js
=> feature-NXP-27995-schemaFilter-master

core/nuxeo-operation.js, core/nuxeo-resource.js
Depends on https://github.com/nuxeo/nuxeo/pull/3408
=> ELEMENTS-1060: no underscore in es sync indexing header

storybook/.storybook/nuxeo-demo-theme.js, ui/nuxeo-data-table/data-table-cell.js, ui/nuxeo-data-table/default-styles.js, ui/nuxeo-data-table/iron-data-table.js
Pipeline: https://qa.nuxeo.org/jenkins/job/web-ui-pipeline-ncunha/256/
=> ELEMENTS-1069: new styling for add entry button on data table

test/index.html
=> fix-ELEMENTS-1093-stab-unit-tests-910

test/index.html
=> fix-ELEMENTS-1093-stab-unit-tests-1010

ui/nuxeo-slots.js, ui/test/nuxeo-slots.test.js
=> fix-ELEMENTS-1096-slot-dom-distribution

ui/test/nuxeo-selectivity.test.js, ui/widgets/nuxeo-selectivity.js
=> fix-ELEMENTS-1090-selectivity-reparent

ui/widgets/nuxeo-user-suggestion.js
=> fix-ELEMENTS-1068-GroupNameWithSpecialCharacters

ui/actions/nuxeo-add-to-collection-button.js
Related to https://github.com/nuxeo/nuxeo-web-ui/pull/808
=> ELEMENTS-1115: ensure collectionId is not reset before firing event

ui/widgets/nuxeo-operation-button.js
=> fix-NXP-28478-showProgressOnBulkDownload

ui/package.json, ui/test/layouts/document/test/nuxeo-test-view-layout.html, ui/test/layouts/dummy-layout.html, ui/test/nuxeo-layout.test.js
=> improvement-ELEMENTS-1094-reenableAndFixNuxeoLayoutTest

storybook/src/elements/nuxeo-tree/nuxeo-tree.stories.js
=> ELEMENTS-1027: add nuxeo tree to story book

storybook/.storybook/config.js, testing-helpers/nuxeo-mock-client.js, testing-helpers/test-helpers.js
Few more improvements needed for being used on WebUI side and also to ensure Storybook runs properly.
=> ELEMENTS-1153: Testing Helper

ui/test/nuxeo-directory-widgets.test.js, ui/widgets/nuxeo-directory-checkbox.js, ui/widgets/nuxeo-directory-radio-group.js
Forced some extra runs/builds on JenkinsX in order to have several checks. The tests seem more stable.
The changes include some small "bug fix" on the `selectedItem(s)` usage.
=> ELEMENTS-1160: stabilize nuxeo-directory-widgets unit tests

ui/widgets/nuxeo-uploader-behavior.js
web-ui PR is: https://github.com/nuxeo/nuxeo-web-ui/pull/895
=> ELEMENTS-1169: expose the batchId in the uploader behavior

core/nuxeo-operation.js, ui/widgets/nuxeo-operation-button.js
Required after https://github.com/nuxeo/nuxeo/commit/b4ca2a2cea57956fd8c5293cdcc2850e2e76006b
=> ELEMENTS-1168: handle download of json async op results

testing-helpers/index.js, testing-helpers/test-helpers.js, ui/test/nuxeo-actions-menu.test.js, ui/test/nuxeo-delete-document-button.test.js, ui/test/nuxeo-directory-widgets.test.js, ui/test/nuxeo-document-comment-thread.test.js, ui/test/nuxeo-error.test.js, ui/test/nuxeo-filter.test.js, ui/test/nuxeo-image-viewer.test.js, ui/test/nuxeo-layout.test.js, ui/test/nuxeo-slots.test.js, ui/test/nuxeo-user-suggestion.test.js, ui/test/nuxeo-user-tag.test.js, ui/test/nuxeo-video-conversions.test.js, ui/test/nuxeo-video-info.test.js
Ended up finding that we may be using `await flush()` more times than needed.
Performed a small cleanup and after it we may want to reassess if we still want to continue with the new wrapped fixture function.
=> improvement-ELEMENTS-1165-FixtureWithFllush

ui/widgets/nuxeo-date-picker.js
Backport https://github.com/nuxeo/nuxeo-ui-elements/pull/480
=> ELEMENTS-1182: set vaadin i18n only once

core/nuxeo-audit-page-provider.js, core/package.json, core/test/nuxeo-audit-page-provider.test.js
PR opened Manually,
This PR is also related to the web-ui one: https://github.com/nuxeo/nuxeo-web-ui/pull/910
=> ELEMENTS-1179: improve the audit page provider filter

nuxeo-operation.html, nuxeo-page-provider.html
🔵 https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/428 with https://github.com/nuxeo/nuxeo-web-ui/commit/b19ddbf2ec11c420c3014ecb674ce8f56aaa558a to set method to post for testing
=> ELEMENTS-1184: allow defining method in nuxeo-page-provider

ui/widgets/nuxeo-selectivity.js
I could not provide a 🔵 pipeline status due to random failures but I will ASAP.
=> ELEMENTS-1189: set relative positioning on multiple input container

ui/nuxeo-document-preview.js
Depends on https://github.com/nuxeo/nuxeo/tree/fix-NXP-29325-blob-preview
=> ELEMENTS-1201: use blob embed preview when available

ui/nuxeo-aggregation/nuxeo-dropdown-aggregation.js, ui/widgets/nuxeo-selectivity.js
=> ELEMENTS-1230: fix overflow in nuxeo-data-table

ui/nuxeo-button-styles.js, ui/nuxeo-user-group-management.js, ui/nuxeo-user-group-management/nuxeo-group-management.js, ui/nuxeo-user-group-management/nuxeo-user-management.js, ui/nuxeo-user-group-management/nuxeo-user-profile.js
I accept suggestions for naming :) (rookie alert 🎉)
=> ELEMENTS-1222: add class for buttons with horizontal icon and label placement

ui/nuxeo-data-table/data-table-column-filter.js
=> fix-ELEMENTS-1214-alignDataTableColumnFilter

storybook/src/elements/nuxeo-textarea/nuxeo-textarea.stories.js
=> imp-ELEMENTS-1243-addNuxeoTextAreaToStorybook

ui/nuxeo-user-group-management/nuxeo-group-management.js
=> fix-ELEMENTS-1251-deleted-group

ui/widgets/nuxeo-selectivity.js
=> fix-ELEMENTS-1250-scrollbarsOnNuxeoDirectorySuggestion

ui/nuxeo-document-permissions/nuxeo-document-permissions.js, ui/nuxeo-document-permissions/nuxeo-popup-permission.js, ui/nuxeo-user-group-management/nuxeo-user-management.js, ui/nuxeo-user-group-management/nuxeo-user-profile.js
Related to https://github.com/nuxeo/nuxeo-web-ui/pull/1069
=> ELEMENTS-1273: apply text style to buttons

ui/viewers/nuxeo-video-viewer.js
Related to https://github.com/nuxeo/nuxeo-web-ui/pull/1065.
=> ELEMENTS-1271: make storyboard position absolute

storybook/src/elements/nuxeo-pagination-controls/nuxeo-pagination-controls.stories.js, ui/nuxeo-pagination-controls.js
Opening PR looking for feedback on:
- are we ok with dropdown? do we prefer input field?
- if there are many options, we're ok with having all in the dropdown?
- should the dropdown be optional?
=> ELEMENTS-1234: add dropdown to select current page

ui/nuxeo-aggregation/nuxeo-checkbox-aggregation.js, ui/widgets/nuxeo-select.js, ui/widgets/nuxeo-selectivity.js
=> ELEMENTS-1276: align carets in dropdown elements

ui/widgets/nuxeo-selectivity.js
Backport of https://github.com/nuxeo/nuxeo-elements/pull/324.
=> ELEMENTS-1270: add escapeHTML to nuxeo-selectivity

core/nuxeo-page-provider.js
Same than https://github.com/nuxeo/nuxeo-elements/pull/318
=> ELEMENTS-1283: fix nuxeo page provider params management

ui/import-href.js
Helper method to import HTML to be used when importing Web UI bundles.
=> ELEMENTS-1289: introduce importHTML

ui/nuxeo-path-suggestion/nuxeo-path-suggestion.js
=> fix-ELEMENTS-1287-path-suggestion-validation

ui/nuxeo-document-preview.js
=> ELEMENTS-1293: rendition for preview applies only to main blob (3.0.x)

ui/nuxeo-path-suggestion/nuxeo-path-suggestion.js
Backport of https://github.com/nuxeo/nuxeo-elements/pull/348
=> ELEMENTS-1305: use custom validator for path validation - 3.0.x

README.md, package.json
Backport of [nuxeo-elements/pull/351](https://github.com/nuxeo/nuxeo-elements/pull/351).
=> ELEMENTS-1303: update node requirements (3.0.x)

README.md, package.json
Backport of [nuxeo-elements/pull/351](https://github.com/nuxeo/nuxeo-elements/pull/351).
=> ELEMENTS-1303: update node requirements (2.4.x)

README.md, package.json
Backport of [nuxeo-elements/pull/351](https://github.com/nuxeo/nuxeo-elements/pull/351).
=> ELEMENTS-1303: update node requirements (2.2.x)

nuxeo-page-provider.html, nuxeo-task-page-provider.html
ELEMENTS-1307 WEBUI-194 (and NXP-30059) go together
This is the ELEMENTS part of the equation
=> ELEMENTS-1307: do not use dots in HTTP headers

ui/nuxeo-routing-behavior.js
babckport of https://github.com/nuxeo/nuxeo-elements/pull/361
=> ELEMENTS-1301: fix by adding a case for array with empty object (3.0.x)

ui/widgets/nuxeo-operation-button.js
Backport of https://github.com/nuxeo/nuxeo-elements/pull/364
=> ELEMENTS-1314: use content-disposition header to download blob when available - 3.0.x

nuxeo-operation.html, test/nuxeo-operation.html
Backport of https://github.com/nuxeo/nuxeo-elements/pull/374
=> ELEMENTS-1318: always send queryParams as an array to the server - 10.10

core/nuxeo-operation.js, core/test/nuxeo-operation.test.js
=> ELEMENTS-1318: always send queryParams as an array to the serve

ui/widgets/nuxeo-operation-button.js
=> fix-ELEMENTS-1324-csv-export-3.0.x

ui/widgets/nuxeo-operation-button.js
=> fix-ELEMENTS-1324-csv-export

core/package.json, dataviz/package.json, package.json, storybook/package.json, testing-helpers/package.json, ui/package.json
=> ELEMENTS-1328: Fix Selectable story of <nuxeo-data-table> (3.0.x)

storybook/.storybook/webpack.config.js
=> ELEMENTS-1319: Fix nuxeo-html-editor demo (3.0.x)

ui/test/nuxeo-date-picker.test.js, ui/widgets/nuxeo-date-picker.js
=> ELEMENTS-1326: fix use of locale in nuxeo-date-picker

ui/nuxeo-data-table/data-table-cell.js, ui/nuxeo-data-table/data-table-checkbox.js
Submitting on behalf of a customer
=> ELEMENTS-1316: Enhance nuxeo-data-table styles

ui/test/nuxeo-date-picker.test.js, ui/widgets/nuxeo-date-picker.js
Backport of https://github.com/nuxeo/nuxeo-elements/pull/382
=> ELEMENTS-1326: use date.get to fix locale usage - 3.0.x

ui/dataviz/nuxeo-document-distribution-chart.js
Backport of https://github.com/nuxeo/nuxeo-elements/pull/394
=> ELEMENTS-1342 - do not include deleted documents by default in distribution chart - 3.0.x

ui/search/nuxeo-search-results-layout.js, ui/test/nuxeo-document-picker.test.js
=> ELEMENTS-1347: Fix picker not working after navigation (3.0.x)

ui/nuxeo-document-preview.js
Backport of [nuxeo-elements/pull/399](https://github.com/nuxeo/nuxeo-elements/pull/399).
=> ELEMENTS-1332: fix preview for documents extending note (3.0.x)

ui/test/nuxeo-html-editor.test.js, ui/widgets/nuxeo-html-editor.js
Backport of https://github.com/nuxeo/nuxeo-elements/pull/412 to 3.0.x.
=> ELEMENTS-1363: show value in readonly html editor (3.0.x)

ui/nuxeo-document-permissions/nuxeo-document-acl-table.js
Backport of https://github.com/nuxeo/nuxeo-elements/pull/414/
=> ELEMENTS-1350: add aclName to Document.RemovePermission request - 3.0.X

core/nuxeo-audit-page-provider.js, core/nuxeo-notify-behavior.js, core/test/nuxeo-notify-behavior.test.js, ui/actions/nuxeo-lock-toggle-button.js, ui/actions/nuxeo-move-documents-down-button.js, ui/actions/nuxeo-move-documents-up-button.js, ui/actions/nuxeo-share-button.js, ui/nuxeo-document-comments/nuxeo-document-comment-thread.js, ui/nuxeo-document-comments/nuxeo-document-comment.js, ui/search/nuxeo-results-view.js, ui/widgets/nuxeo-operation-button.js
Backport of https://github.com/nuxeo/nuxeo-elements/pull/418 to 3.0.x.
=> ELEMENTS-1368: make notification possible for disconnected elements (3.0.x

core/config.js, core/nuxeo-elements.js, core/nuxeo-page-provider.js, ui/nuxeo-filter.js, ui/nuxeo-format-behavior.js, ui/nuxeo-page-provider-display-behavior.js, ui/nuxeo-routing-behavior.js, ui/test/nuxeo-date.test.js, ui/test/nuxeo-document-suggestion.test.js, ui/test/nuxeo-routing-behavior.test.js, ui/widgets/nuxeo-date-picker.js, ui/widgets/nuxeo-date.js
Backport of https://github.com/nuxeo/nuxeo-elements/pull/407 for 3.0.x.
=> ELEMENTS-1360: add ui configuration registry (3.0.x)

core/config.js, core/test/config.test.js
Backport of https://github.com/nuxeo/nuxeo-elements/pull/429
=> ELEMENTS-1382: fix configuration boolean property parsing - 3.0.x

ui/nuxeo-filter.js
Backport of https://github.com/nuxeo/nuxeo-elements/pull/435.
=> ELEMENTS-1388: make expressions.eval true by default

ui/search/nuxeo-results-view.js
Backport of https://github.com/nuxeo/nuxeo-elements/pull/442
=> ELEMENTS-1394: change headers property type to object - 3.0.x

ui/nuxeo-layout.js
Backport of https://github.com/nuxeo/nuxeo-elements/pull/447
=> ELEMENTS-1393: filter out non visible inputs for layout validation
